### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by TNT911** [manu7irl/klipper-DWC2-installer#10]
Getting the following error:

###### Creating some folders...
./installer.sh: line 232: syntax error near unexpected token `else'

**Comment by changedsoul** [comment]
Same error for me. Tried the old script to update klipper and dwc and was left with a broken printer. Came here to update the installer hoping there was a fix and see it was updated yesturday....yipie!!! only to get this error too and now Im bummed, lol

**Comment by exxperto** [comment]
I'm not sure, but you can try change lines 229- 231 

~~if [ $session_num == 0 ]
then
            if [ -f $installLocation/printer.cfg ] && report_status "Moving and renaming your printer.cfg to the correct folder... under $PRINTER_FOLDER/"; sleep 3 && mv $installLocation/printer.cfg $KlipperFarm/$PRINTER_FOLDER~~

to this:

`if [ $session_num == 0 ] && [ -f $installLocation/printer.cfg ]; then report_status "Moving and renaming your printer.cfg to the correct folder... under $PRINTER_FOLDER/" && sleep 3 && mv $installLocation/printer.cfg $KlipperFarm/$PRINTER_FOLDER
`

**Comment by julien-w** [comment]
Same error here...

**Comment by manu7irl** [comment]
corrected that! fixed 3 commits ago, test and report, thanks!
