### ISSUE TITLE
Stopping klipper-0 service...

### ISSUE THREAD

**Issue by damanbaird** [manu7irl/klipper-DWC2-installer#13]
ERROR: Failed to stop klipper-0.service: Unit klipper-0.service not loaded
 done on fresh Raspberry Pi OS install 
Klipper installed fine, went to "flash your MCU" and got this.

**Comment by manu7irl** [comment]
If you got first step successful, you should not have an error about a
missing klipper-0.service.
As the first step created it.
So eventually the first step was to blame.
Try from scratch the first step should let you stay in the script and also
prompt about a klipper-0 service that is running.

**Comment by damanbaird** [comment]
Ok, let have another go at it, and ill keep you posted, thanks!

**Comment by manu7irl** [comment]
I think, I spotted a little problem, I will fix it this saturday.
As a workaround create a blank printer.cfg file in your user folder.
/home/pi/printer.cfg
As my script tries to move over my new folder structure.

**Comment by damanbaird** [comment]
I tried 3 more times before it finally said it was installed. Have one more issue though.

**Comment by damanbaird** [comment]
I have no idea what i did but it has been working now.

**Comment by klHaribo** [comment]
I have the same error now, thinking to give up.
as an alternative, is it possible that the script uses the "/etc/init.d/klipper stop" command?
the first try, the script stops because ~/PrinterFarm/KlipperFarm does not exist...

another improvement: instead asking for the user, the script could ask the "whoami" command?

**Comment by notp1ssed** [comment]
I am getting this same error, any idea why?

**Comment by damanbaird** [comment]
Try from a fresh install again, think i tried 3 times before it went right for me.

**Comment by notp1ssed** [comment]
> Try from a fresh install again, think i tried 3 times before it went right for me.

I didn't have enough memory on sd card I guess. I was trying initially on a 4gb sd card. Then swapped to a 16 GB card and this error was gone. thanks anyway
