### ISSUE TITLE
New Install

### ISSUE THREAD

**Issue by shadrincev** [manu7irl/klipper-DWC2-installer#2]
Good afternoon. Thank you for your work. I would like to correct a more correct installation in the README file

```
cd ~
git clone https://github.com/manu7irl/klipper-DWC2-installer
./klipper-DWC2-installer/klipper-dwc2-install.sh

```
Then next when prompted

=================================
KLIPPER SERVICE INSTALL FOR SOC:
---------------------------------
Please choose the install needed:
(1)install-beaglebone.sh
(2)install-centos.sh
(3)install-debian.sh
(4)install-octopi.sh
(Q)uit
---------------------------------

need to select (4)install-octopi.sh

And update the line
`wet https://github.com/chrishamm/DuetWebControl/releases/download/2.0.4/DuetWebControl-SD.zip`
on
`wget https://github.com/chrishamm/DuetWebControl/releases/download/2.0.6/DuetWebControl-SBC.zip`
so how did the update come out.
thank you.

**Comment by manu7irl** [comment]
Hi, thanks for using my script, actually these scripts are not mine but cloned for klipper github in folder:
~/klipper/scripts/ so the typo is not related to me...
But the line your are pointing to is not inside the install-octopi.sh,
it is a line in DWC install script.
I will check if there is a typo there...
I made some pretty big changes yesterday,
run a git pull from within my script folder and you will get a whole new experience!
try it safe and print fast!!
