### ISSUE TITLE
URL to duetwebcontrol wrong

### ISSUE THREAD

**Issue by exxperto** [manu7irl/klipper-DWC2-installer#4]
This URL incorrect too:
https://github.com/manu7irl/klipper-DWC2-installer/blob/1e6b85f446c903752d8ae2e9a3af5040f4ded5b6/installer.sh#L476

You changed only dwc_update script :) 

Maybe it will be easy to define it at top in one place?

**Comment by manu7irl** [comment]
You're right totally missed that.
