### ISSUE TITLE
Installer.sh permission denied

### ISSUE THREAD

**Issue by jjuuzzii** [manu7irl/klipper-DWC2-installer#5]
When I execute installer.sh i can choose the different options if I choose one I get mkdir permission denied

**Comment by manu7irl** [comment]
Did you type your user name at the question prompt?
Did you check that you entered it correctly?

**Comment by jjuuzzii** [comment]
Which username promt?

**Comment by manu7irl** [comment]
When you launch the script.
There are 2 questions to answer.

**Comment by jjuuzzii** [comment]
You can close it!

**Comment by manu7irl** [comment]
Ok thanks!

**Comment by jjuuzzii** [comment]
Damm I could have been so easy!

**Comment by manu7irl** [comment]
Glad you like it.
