### ISSUE TITLE
Invoking of the Webinterface isn't possible

### ISSUE THREAD

**Issue by Peuqui** [manu7irl/klipper-DWC2-installer#7]
...even with a clean installation described from here: https://klipper.info/klipper-+-dwc2-1/installing-klipper-with-dwc2 or with your scripts, also fresh and clean installed.
Then I tried to follow the "solutions" on several issues tracked from the original github sources and your responses there.
-> no luck.

With Octoprint and the correspondent plugin, it runs smooth. But I wanted to go to DWC2...

**Comment by manu7irl** [comment]
Did check for errors in your klippy-0.log?

**Comment by Peuqui** [comment]
I got to manage to sort out this issue: Was a config error in regard of the serial connection: the [mcu] was doubled in the printer-0.cfg, so that klippy won't start.

Sorry for that!

**Comment by notp1ssed** [comment]
I am having this same error, and double MCU is not the problem here, what more could it be?
