### ISSUE TITLE
Proposal: Change the Klippy Log to be stored on the virtual SD card for DWC

### ISSUE THREAD

**Issue by lukeslaboratory** [manu7irl/klipper-DWC2-installer#9]
Hey - I was just doing some updates to my config and I think it would be another neat step if the log file could be changed to be stored in the virtual SD card, where it could be seen by DWC under sys and you could interact with it there.  It beats every time needing to SSH into the machine to review and delete the klippy log when tracking down issues.

Thanks!

**Comment by tripstar76** [comment]
Create a symlink....

ln -s /tmp/klippy.log ~/sdcard/sys/klippy.log

**Comment by manu7irl** [comment]
good point I can add this, to the script.

**Comment by manu7irl** [comment]
I added that on the last commit, please test if you see your log file in there...

**Comment by manu7irl** [comment]
corrected a bad copy paste... now it should work..
